// examples/vue-example/src/App.vue
<script setup lang="ts">
import * as stylex from '@stylexjs/stylex'
import { colors } from '@stylexjs/open-props/lib/colors.stylex'
import { sizes } from '@stylexjs/open-props/lib/sizes.stylex'
import { fonts } from '@stylexjs/open-props/lib/fonts.stylex'
</script>

<script lang="ts">
const styles = stylex.create({
  main: {
    width: '100vw',
    height: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.pink7,
  },
  card: {
    backgroundColor: colors.blue9,
    padding: sizes.spacing5,
    borderRadius: sizes.spacing2,
    justifyContent: 'center',
    display: 'flex',
    alignItems: 'center',
    color: colors.gray0,
    fontFamily: fonts.mono,
  },
})
</script>

<template>
  <div :class="stylex.props(styles.main).className">
    <div :class="stylex.props(styles.card).className">
      <span>Blue rounded rectangle</span>
    </div>
  </div>
</template>

// examples/svelte-example/src/app.svelte
<script lang="ts">
  import { colors } from '@stylexjs/open-props/lib/colors.stylex'
  import { fonts } from '@stylexjs/open-props/lib/fonts.stylex'
  import { sizes } from '@stylexjs/open-props/lib/sizes.stylex'
  import * as stylex from '@stylexjs/stylex'

  const styles = stylex.create({
    main: {
      width: '100vw',
      height: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.pink7,
    },
    card: {
      backgroundColor: colors.blue9,
      padding: sizes.spacing5,
      borderRadius: sizes.spacing2,
      justifyContent: 'center',
      display: 'flex',
      alignItems: 'center',
      color: colors.gray0,
      fontFamily: fonts.mono,
    },
  })
</script>

<main>
  <div class={stylex.props(styles.main).className}>
    <div class={stylex.props(styles.card).className}>
      <span>Blue rounded rectangle</span>
    </div>
  </div>
</main>
